<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\props\netcore.props" />
    <Import Project="..\..\props\common.props" />
    <Import Project="..\..\props\test.props" />

    <ItemGroup>
        <ProjectReference Include="..\..\src\XiHan.Framework.SearchEngines.Elasticsearch\XiHan.Framework.SearchEngines.Elasticsearch.csproj" />
    </ItemGroup>

</Project>
