<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\props\netcore.props" />
	<Import Project="..\..\props\common.props" />
	<Import Project="..\..\props\test.props" />

	<ItemGroup>
		<ProjectReference Include="..\..\src\XiHan.Framework.Domain\XiHan.Framework.Domain.csproj" />
		<ProjectReference Include="..\..\src\XiHan.Framework.Domain.Shared\XiHan.Framework.Domain.Shared.csproj" />
		<ProjectReference Include="..\..\src\XiHan.Framework.Core\XiHan.Framework.Core.csproj" />
	</ItemGroup>

</Project>
