<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\props\netcore.props" />
	<Import Project="..\..\props\common.props" />
	<Import Project="..\..\props\test.props" />

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.12" />
	  <ProjectReference Include="..\..\src\XiHan.Framework.Web.Api\XiHan.Framework.Web.Api.csproj" />
	</ItemGroup>


</Project>
