// Copyright (c) 2021-Present XiHanFun and contributors.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using Microsoft.CodeAnalysis.Text;

namespace XiHan.Framework.Analyzers.FileHeaders;

internal static class XiHanFileHeader
{
    private const string FirstLine = "// Copyright (c) 2021-Present XiHanFun and contributors.";
    private const string SecondLine = "// Licensed under the MIT License. See LICENSE in the project root for license information.";

    /// <summary>
    /// 统一的两行文件头（每行以换行结尾）。
    /// </summary>
    internal const string HeaderText = FirstLine + "\n" + SecondLine + "\n";

    /// <summary>
    /// 校验源文件是否以标准的两行版权与授权声明开头。
    /// </summary>
    internal static bool IsValid(SourceText sourceText)
    {
        var text = NormalizeLineEndings(RemoveByteOrderMark(sourceText.ToString()));
        return text.StartsWith(HeaderText, StringComparison.Ordinal);
    }

    /// <summary>
    /// 判断是否跳过分析（非 .cs、bin/obj、生成代码等）。
    /// </summary>
    internal static bool ShouldSkip(string? filePath, SourceText sourceText)
    {
        if (string.IsNullOrWhiteSpace(filePath) || !string.Equals(Path.GetExtension(filePath), ".cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var actualFilePath = filePath!;
        var normalizedPath = actualFilePath.Replace(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar);
        if (normalizedPath.IndexOf($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase) >= 0 ||
            normalizedPath.IndexOf($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            return true;
        }

        var fileName = Path.GetFileName(actualFilePath);
        if (fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
            fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) ||
            fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var leadingTextLength = Math.Min(sourceText.Length, 2048);
        if (leadingTextLength == 0)
        {
            return false;
        }

        var leadingText = sourceText.GetSubText(new TextSpan(0, leadingTextLength)).ToString();
        return leadingText.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0;
    }

    /// <summary>
    /// 定位需要被替换的既有版权头区间：文件顶部以 “// Copyright” 起始的连续注释行，含其后的一个空行。
    /// 未识别到则返回 false，交由调用方在文件顶部插入。
    /// </summary>
    internal static bool TryGetHeaderSpan(SourceText sourceText, out TextSpan span)
    {
        var text = sourceText.ToString();
        var bomOffset = text.StartsWith("\uFEFF", StringComparison.Ordinal) ? 1 : 0;

        if (!SubstringStartsWith(text, bomOffset, "// Copyright"))
        {
            span = default;
            return false;
        }

        var pos = bomOffset;
        while (pos < text.Length && SubstringStartsWith(text, pos, "//"))
        {
            var newLineIndex = text.IndexOf('\n', pos);
            if (newLineIndex < 0)
            {
                pos = text.Length;
                break;
            }

            pos = newLineIndex + 1;
        }

        // 吞掉版权头后的一个空行，避免替换后残留多余空行。
        if (pos < text.Length && text[pos] == '\n')
        {
            pos++;
        }
        else if (pos + 1 < text.Length && text[pos] == '\r' && text[pos + 1] == '\n')
        {
            pos += 2;
        }

        span = TextSpan.FromBounds(0, pos);
        return true;
    }

    /// <summary>
    /// 构建标准文件头（两行声明 + 一个空行）。
    /// </summary>
    internal static string CreateHeader()
    {
        return HeaderText + "\n";
    }

    internal static string GetFileName(string? filePath)
    {
        if (string.IsNullOrWhiteSpace(filePath))
        {
            return string.Empty;
        }

        return Path.GetFileNameWithoutExtension(filePath);
    }

    private static bool SubstringStartsWith(string text, int index, string value)
    {
        if (index < 0 || index + value.Length > text.Length)
        {
            return false;
        }

        return string.CompareOrdinal(text, index, value, 0, value.Length) == 0;
    }

    private static string RemoveByteOrderMark(string text)
    {
        return text.StartsWith("\uFEFF", StringComparison.Ordinal)
            ? text.Substring(1)
            : text;
    }

    private static string NormalizeLineEndings(string text)
    {
        return text
            .Replace("\r\n", "\n")
            .Replace("\r", "\n");
    }
}
