#region <<版权版本注释>>

// ----------------------------------------------------------------
// Copyright ©2021-Present ZhaiFanhua All Rights Reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// FileName:XiHanFileHeader
// Guid:3f59618c-4677-4c3d-9407-f01e2792fd20
// Author:zhaifanhua
// Email:me@zhaifanhua.com
// CreateTime:2026/04/26 17:33:31
// ----------------------------------------------------------------

#endregion <<版权版本注释>>

using System.Globalization;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis.Text;

namespace XiHan.Framework.Analyzers.FileHeaders;

internal static class XiHanFileHeader
{
    private const string NewLine = "\n";
    private const string RegionStart = "#region <<版权版本注释>>";
    private const string RegionEnd = "#endregion <<版权版本注释>>";
    private const string DateTimeFormat = "yyyy/MM/dd HH:mm:ss";

    private static readonly Regex StrictHeaderRegex = new(
        @"\A#region <<版权版本注释>>\n\n" +
        @"// ----------------------------------------------------------------\n" +
        @"// Copyright ©2021-Present ZhaiFanhua All Rights Reserved\.\n" +
        @"// Licensed under the MIT License\. See LICENSE in the project root for license information\.\n" +
        @"// FileName:(?<fileName>[^\r\n]+)\n" +
        @"// Guid:(?<guid>[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})\n" +
        @"// Author:zhaifanhua\n" +
        @"// Email:me@zhaifanhua\.com\n" +
        @"// CreateTime:(?<createTime>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2})\n" +
        @"// ----------------------------------------------------------------\n\n" +
        @"#endregion <<版权版本注释>>\z",
        RegexOptions.Compiled);

    private static readonly Regex GuidRegex = new(
        @"(?m)^// Guid:(?<value>[^\r\n]+)$",
        RegexOptions.Compiled);

    private static readonly Regex CreateTimeRegex = new(
        @"(?m)^// CreateTime:(?<value>[^\r\n]+)$",
        RegexOptions.Compiled);

    internal static bool IsValid(SourceText sourceText, string filePath)
    {
        if (!TryGetHeaderSpan(sourceText, out var headerSpan))
        {
            return false;
        }

        var headerText = sourceText.GetSubText(headerSpan).ToString();
        var normalizedHeader = NormalizeLineEndings(RemoveByteOrderMark(headerText)).TrimEnd('\n');
        var match = StrictHeaderRegex.Match(normalizedHeader);
        if (!match.Success)
        {
            return false;
        }

        var expectedFileName = GetFileName(filePath);
        if (!string.Equals(match.Groups["fileName"].Value, expectedFileName, StringComparison.Ordinal))
        {
            return false;
        }

        if (!Guid.TryParseExact(match.Groups["guid"].Value, "D", out _))
        {
            return false;
        }

        return DateTime.TryParseExact(
            match.Groups["createTime"].Value,
            DateTimeFormat,
            CultureInfo.InvariantCulture,
            DateTimeStyles.None,
            out _);
    }

    internal static bool ShouldSkip(string? filePath, SourceText sourceText)
    {
        if (string.IsNullOrWhiteSpace(filePath) || !string.Equals(Path.GetExtension(filePath), ".cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var actualFilePath = filePath!;
        var normalizedPath = actualFilePath.Replace(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar);
        if (normalizedPath.IndexOf($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase) >= 0 ||
            normalizedPath.IndexOf($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            return true;
        }

        var fileName = Path.GetFileName(actualFilePath);
        if (fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
            fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) ||
            fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var leadingTextLength = Math.Min(sourceText.Length, 2048);
        if (leadingTextLength == 0)
        {
            return false;
        }

        var leadingText = sourceText.GetSubText(new TextSpan(0, leadingTextLength)).ToString();
        return leadingText.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0;
    }

    internal static bool TryGetHeaderSpan(SourceText sourceText, out TextSpan span)
    {
        var text = sourceText.ToString();
        var startOffset = text.StartsWith("\uFEFF", StringComparison.Ordinal) ? 1 : 0;

        if (!text.Substring(startOffset).StartsWith(RegionStart, StringComparison.Ordinal))
        {
            span = default;
            return false;
        }

        var endIndex = text.IndexOf(RegionEnd, startOffset, StringComparison.Ordinal);
        if (endIndex < 0)
        {
            span = default;
            return false;
        }

        var endPosition = endIndex + RegionEnd.Length;
        endPosition = ConsumeNewLine(text, endPosition);

        if (endPosition < text.Length && IsNewLineStart(text, endPosition))
        {
            endPosition = ConsumeNewLine(text, endPosition);
        }

        span = TextSpan.FromBounds(0, endPosition);
        return true;
    }

    internal static HeaderMetadata ReadExistingMetadata(SourceText sourceText)
    {
        if (!TryGetHeaderSpan(sourceText, out var headerSpan))
        {
            return HeaderMetadata.Empty;
        }

        var headerText = NormalizeLineEndings(sourceText.GetSubText(headerSpan).ToString());
        var guid = ReadGuid(headerText);
        var createTime = ReadCreateTime(headerText);
        return new HeaderMetadata(guid, createTime);
    }

    internal static string CreateHeader(string fileName, Guid guid, DateTime createTime)
    {
        return string.Join(NewLine, new[]
        {
            RegionStart,
            string.Empty,
            "// ----------------------------------------------------------------",
            "// Copyright ©2021-Present ZhaiFanhua All Rights Reserved.",
            "// Licensed under the MIT License. See LICENSE in the project root for license information.",
            $"// FileName:{fileName}",
            $"// Guid:{guid:D}",
            "// Author:zhaifanhua",
            "// Email:me@zhaifanhua.com",
            $"// CreateTime:{createTime.ToString(DateTimeFormat, CultureInfo.InvariantCulture)}",
            "// ----------------------------------------------------------------",
            string.Empty,
            RegionEnd,
            string.Empty,
            string.Empty,
        });
    }

    internal static string GetFileName(string? filePath)
    {
        if (string.IsNullOrWhiteSpace(filePath))
        {
            return string.Empty;
        }

        return Path.GetFileNameWithoutExtension(filePath);
    }

    private static Guid? ReadGuid(string headerText)
    {
        var match = GuidRegex.Match(headerText);
        if (!match.Success)
        {
            return null;
        }

        return Guid.TryParseExact(match.Groups["value"].Value.Trim(), "D", out var guid)
            ? guid
            : null;
    }

    private static DateTime? ReadCreateTime(string headerText)
    {
        var match = CreateTimeRegex.Match(headerText);
        if (!match.Success)
        {
            return null;
        }

        return DateTime.TryParseExact(
            match.Groups["value"].Value.Trim(),
            DateTimeFormat,
            CultureInfo.InvariantCulture,
            DateTimeStyles.None,
            out var createTime)
            ? createTime
            : null;
    }

    private static string RemoveByteOrderMark(string text)
    {
        return text.StartsWith("\uFEFF", StringComparison.Ordinal)
            ? text.Substring(1)
            : text;
    }

    private static string NormalizeLineEndings(string text)
    {
        return text
            .Replace("\r\n", "\n")
            .Replace("\r", "\n");
    }

    private static bool IsNewLineStart(string text, int position)
    {
        return position < text.Length && (text[position] == '\r' || text[position] == '\n');
    }

    private static int ConsumeNewLine(string text, int position)
    {
        if (position >= text.Length)
        {
            return position;
        }

        if (text[position] == '\r')
        {
            position++;
            if (position < text.Length && text[position] == '\n')
            {
                position++;
            }

            return position;
        }

        return text[position] == '\n' ? position + 1 : position;
    }
}

internal readonly struct HeaderMetadata
{
    internal static HeaderMetadata Empty { get; } = new(null, null);

    internal HeaderMetadata(Guid? guid, DateTime? createTime)
    {
        Guid = guid;
        CreateTime = createTime;
    }

    internal Guid? Guid { get; }

    internal DateTime? CreateTime { get; }
}
